/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GUI;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.File;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {

        FXMLLoader fxmlLoader = new FXMLLoader(new File("src/main/resources/GUI/main-view.fxml").toURI().toURL());
        Scene scene = new Scene(fxmlLoader.load(), 800, 600);

        stage.setTitle("Map of Denmark");
        stage.setScene(scene);
        stage.show();
    }
}
